name: tictactoe
version: '${project.version}'
main: me.l00pz.tictactoe.tictactoe.tictactoe
api-version: 1.18
commands:
  challenge:
    description: starts tictactoe game
    usage: /<command> <p2>
    aliases: [ttt]
  accept:
    description: accepts request
    usage: /<command>
    aliases: [a]
  deny:
    description: denies request
    usage: /<command>
    aliases: [d]
  put:
    description: use this instead of touching the board
    usage: /<command> <num>
    aliases: [p]
  save:
    description: saves the game
    usage: /<command> <gameNum>
    aliases: [s]
  load:
    description: loads the game
    usage: /<command> <gameNum>
    aliases: [l]